[build]
  base = "/"
  publish = "./build"
  command = "pnpm run build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20.13.1"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200